version: "3.7"

services:
  api1: # API - Instância 01
    image: lucaswilliameufrasio/backend-cockfighting-bun-api
    hostname: api1
    restart: unless-stopped
    environment:
      - PORT=80
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fight
      - DB_USER=postgres
      - DB_PASSWORD=fight
      - DB_MAX_CONNECTIONS=75
    depends_on:
      - db
    expose:
      - "80"
    networks:
      - fight-pit
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

  api2: # API - Instância 02
    image: lucaswilliameufrasio/backend-cockfighting-bun-api
    hostname: api2
    restart: unless-stopped
    environment:
      - PORT=80
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fight
      - DB_USER=postgres
      - DB_PASSWORD=fight
      - DB_MAX_CONNECTIONS=75
    depends_on:
      - db
    expose:
      - "80"
    networks:
      - fight-pit
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

  nginx: # Load Balancer
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - fight-pit
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.4GB'

  db:
    image: postgres:15
    hostname: db
    container_name: backend-cockfighting-bun-database
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=fight
      - POSTGRES_DB=fight
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/postgresql.conf:/etc/postgresql/postgresql.conf

    ports:
      - 5459:5432
    networks:
      - fight-pit
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    hostname: dragonfly
    container_name: backend-cockfighting-bun-cache
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
    restart: unless-stopped
    # ulimits:
    #   memlock: -1
    volumes:
      - dragonfly_data:/data
    ports:
      - 6380:6379
    networks:
      - fight-pit
    # healthcheck:
    #   test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    #   interval: 1s
    #   timeout: 3s
    #   retries: 30

networks:
  fight-pit:
    driver: bridge

volumes:
  postgres_data:
  dragonfly_data:
