version: "3.7"

services:
  postgres:
    image: postgres:15
    container_name: backend-cockfighting-bun-dev-database
    restart: always
    environment: 
      - POSTGRES_PASSWORD=fight
      - POSTGRES_DB=fight
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5458:5432
    networks:
      - fight-pit
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    hostname: dragonfly
    container_name: backend-cockfighting-bun-cache
    restart: unless-stopped
    volumes:
      - dragonfly_data:/data
    ports:
      - 6380:6379
    networks:
      - fight-pit
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

networks:
  fight-pit:
    driver: bridge

volumes:
  postgres_data:
  dragonfly_data:
