name: main

on:
  push:
    branches: [ benchmark ]

jobs:
  # build:
  #   runs-on: ubuntu-22.04
    

  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Build
  #       run: make build-app && make build-image

  test:
    runs-on: ubuntu-22.04

    # needs: build

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - run: docker-compose up -d

    - name: Load test
      run: |
        git clone --single-branch --quiet https://github.com/zanfranceschi/rinha-de-backend-2023-q3
        cd rinha-de-backend-2023-q3
        wget https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.5/gatling-charts-highcharts-bundle-3.9.5-bundle.zip
        unzip gatling-charts-highcharts-bundle-3.9.5-bundle.zip
        cd gatling-charts-highcharts-bundle-3.9.5
        sleep 15
        ./bin/gatling.sh -rm local -s RinhaBackendSimulation -rd "${{ github.sha }}" -rf $WORKSPACE/user-files/results -sf $WORKSPACE/user-files/simulations -rsf $WORKSPACE/user-files/resources
        echo GATLING_OUTPUT_FOLDER=$(ls $WORKSPACE/user-files/results | sort | head -n 1) >> $GITHUB_ENV
      env:
        WORKSPACE: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test

    - run: docker-compose ps

    - run: docker-compose logs

    - run: curl -v "http://localhost:9999/contagem-pessoas"

    - run: docker-compose down

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test/user-files/results/${{ env.GATLING_OUTPUT_FOLDER }}
        destination_dir: ${{ env.GATLING_OUTPUT_FOLDER }}
  
    - run: echo "GH_REPO=$(echo ${{ github.repository }} | cut -d "/" -f 2)" >> $GITHUB_ENV

    - run: echo "[Deploying to https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }}](https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }})" >> "${GITHUB_STEP_SUMMARY}"
